version: '3.8'

services:
  laravel-email-archive:
    image: laravel-email-archive
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-email-archive
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - huntress

  laravel-email-archive-nginx:
    image: nginx:alpine
    container_name: laravel-email-archive-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - huntress

  laravel-email-archive-mysql:
    image: mysql:latest
    container_name: laravel-email-archive-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_email_archive
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/dbdata/:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - huntress

networks:
  huntress:
    driver: bridge

volumes:
  dbdata:
    driver: local
